use_frameworks!

platform :ios, '8.0'

target 'TheCocoaHTTPServer_Example' do
  pod 'TheCocoaHTTPServer', :path => '../'

  target 'TheCocoaHTTPServer_Tests' do
    inherit! :search_paths

    
  end
end
